### ISSUE TITLE
Issues with npm install

### ISSUE THREAD

**Issue by rrshaban** [IonicaBizau/github-emojify#1]
Trying to run `npm i -g github-emojify` raises "No compatible version found" on  `github-emojify@'*'`. To get the installer to run I had to specify `npm i -g github-emojify@1.0.0-beta`.

**Comment by IonicaBizau** [comment]
@rrshaban Whoups, I forgot to `npm publish` the version `1.0.0`. :sparkle: Thanks for heads-up! :+1: It should be fine now.
